### ISSUE TITLE
Fix dependency installation for first time installation

### ISSUE THREAD

**Issue by IamPhytan** [leoheck/kiri#100]
Hello,

There is an issue when installing dependencies with the command from [INSTALL.md](https://github.com/leoheck/kiri/blob/main/INSTALL.md) :
```bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_dependencies.sh)"
```

When installing Python dependencies, the `install_dependencies.sh` script requires a `python-requirements.txt` file that is not necessarily available when installing `kiri` for the first time or when updating the dependencies outside the repository.
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'python-requirements.txt'
```

This is due to how the script expects that `python-requirements.txt` is in the current working directory. 
https://github.com/leoheck/kiri/blob/0debee1864bba5a79132e5a790c01d908c9fa3eb/install_dependencies.sh#L221-L222

**Comment by leoheck** [comment]
Hm, that's true, makes sense. Thanks for fixing this.
