### ISSUE TITLE
Installing kiri on Ubuntu (Command 'kiri' not found, did you mean:)

### ISSUE THREAD

**Issue by radiolyc** [leoheck/kiri#102]
Hi! I'm trying to install **kiri** on Ubuntu system, but it doesn't work for me.
1) Firstly, I've just opened terminal and installed all dependencies:
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_dependencies.sh)"`
![1](https://github.com/leoheck/kiri/assets/132251049/58229d63-24a2-47c2-908b-253d906cf9f0)
2) Then I installed **kiri** itself
`bash -c "INSTALL_KIRI_REMOTELLY=1; \
    $(curl -fsSL https://raw.githubusercontent.com/leoheck/kiri/main/install_kiri.sh)"`
![Screenshot from 2023-10-06 15-21-12](https://github.com/leoheck/kiri/assets/132251049/57767c21-3313-4ce6-bf48-50366233c4b9)
3) But when I'm trying to call:
`kiri -h`
It says, that it doesn't exist.
![3](https://github.com/leoheck/kiri/assets/132251049/e84db9c4-1848-490b-a348-1511abee3aff)
I tried do it several times, but with no success. Maybe I miss something?

**Comment by leoheck** [comment]
hi @radiolyc after installing It you have to customize your terminal.

Copy and paste these lines 

![Screenshot_20231006-195759](https://github.com/leoheck/kiri/assets/1277920/a4c8e5f9-3a13-49a0-aeab-394a0a4b901e)

Or add them to the `~/.bashrc` so it will be available next time when you launch the terminal.

**Comment by radiolyc** [comment]
@leoheck Thanks, now it works!
![Screenshot from 2023-10-07 14-23-35](https://github.com/leoheck/kiri/assets/132251049/0fa14421-26b7-4263-b8dd-ecc56a21cdc2)
![Screenshot from 2023-10-07 14-22-58](https://github.com/leoheck/kiri/assets/132251049/19dc253c-e406-415f-b862-dfbe57caa527)
