### ISSUE TITLE
Issues reported on KiBot integration

### ISSUE THREAD

**Issue by leoheck** [leoheck/kiri#104]
This discussion is happening here https://github.com/INTI-CMNB/KiBot/issues/391
I am just summarizing here the issues that are being listed there.

- [x] 1. dos2unix is really needed? 
- [x] 2. when plotkicadsch is missing, then Xdotool is used. If it fails the keyboard is left changed to US.
- [x] 3. It would be nice if --kicad-cli could force the use of kicad-cli even for KiCad 5 files.
- [x] 4. Layout does not have changes when using this command `kiri -D --kicad-cli -l`
- [ ] 5. Just a single instance of the schematics pages is being displayed, and this may hide changes (refdes, values maybe).
- [x] 6. Performance issues with kiri output on large projects with large schematics.

Notes:

1. Definitely not, dependency was removed.
2. This was addressed and the improvement was already pushed.
3. It does, the detail is that kicad-cli does not work for Kicad 5 schematics. 
4. The fix was pushed, and the output looks way better now.
5.
6. This was improved by optimizing svgs with svgo, if it is available.

**Comment by leoheck** [comment]
yeah but I cannot recordist this. are you using mouse?

**Comment by Nudelsalad** [comment]
Yes I am using mouse. It appears to be only when hovering over the third item in the list. Sry that my mouse is not visible, but the flickering was always when hovering over the 3rd item below the schematic and pcb symbol

[Screencast from 12.12.2023 06:14:21.webm](https://github.com/leoheck/kiri/assets/64224137/9819204d-0c65-44ee-a4a1-2d5a3d06d5d6)

when selecting the third one, it is also flickering when hovering over the third one
