### ISSUE TITLE
KiCAD 8.0 Support

### ISSUE THREAD

**Issue by OmegaRogue** [leoheck/kiri#110]
Now that 8.0 is out, are there plans to update this to support kicad 8.0?

**Comment by leoheck** [comment]
It already supports it, even before Kicad 8 is released. What is missing?

**Comment by leoheck** [comment]
What is not working? If it is the layout... then can you try running it this way:
```
kiri -r -D -k -t 4
```

This will plot the layout using `kicad-cli` (flag `-f`) but this takes more time, then `-t 4` will limit the process to the last N commits.

**Comment by OmegaRogue** [comment]
ah, sorry, i thought i remembered there being a kicad plugin, but thats not the case

**Comment by leoheck** [comment]
it can bem added as a plugin, but not in the package manager. the repo has a script to do that.
