### ISSUE TITLE
Python port RFC

### ISSUE THREAD

**Issue by KubaO** [leoheck/kiri#118]
Would a Python port that doesn't need bash, and thus would be much easier to run on Windows, be something worth doing? I've done some work on that and am using it in-house. It will need more work before being ready for wider testing. If that's a direction the project would consider worthwhile, I'd take some time to work on it.

Ideally, I'd like Python as the only major dependency besides git, with necessary packages bundled, and have it runnable without installation, i.e. directly from a git checkout. The "main application" would have a CLI as it has now, and a minimal GUI that provides feedback, launches the file picker and browser, etc. The GUI would be tk-based to minimize dependencies.

Plan:

- [ ] Cleanly port the exiting bash scripts to Python with minimal refactoring, and ensure that they work on all platforms. This wouldn't do much except dropping bash and awk (?) as dependencies. The architecture remains.
- [ ] Add pure Python dependencies as submodules or sources checked into the codebase. The aim is to make it work for KiCad 7 and 8 with Python, git and KiCad as the only dependencies.
- [ ] Refactor the scripts into a single application, potentially removing some dependencies if feasible.
- [ ] Add the optional GUI.
- [ ] Further cull dependencies if at all possible. KiCad has Python library code for accessing design databases, with backwards-compatibility. It should be possible eventually to make the application self-standing, i.e. with no dependencies other than Python, git, and KiCad libraries needed by the project (not even a KiCad binary).

**Comment by leoheck** [comment]
I think redesign using python would be good. However I am not going to change Kiri. It is a bit complex task and I don't use this tool that much to justify this change. However feel free to start a new project to implement what you are proposing. Based on what you said it may be really good. Also, since it can be just a python script it can be easily added to Kicad's addon manager.
