### ISSUE TITLE
cp: directory /path/to/project/kiri/web does not exist

### ISSUE THREAD

**Issue by edahlseng** [leoheck/kiri#25]
When running `kiri --remove ./project.pro`, I'm getting the following error message:

```
Assembling the HTML
cp: directory /path/to/project/kiri/web does not exist
< many more error messages much like this >
```

Any ideas on what might be causing this? (I moved into a path that doesn't have spaces, just to be sure! :smile: )

**Comment by edahlseng** [comment]
Looks like the `web` directory creation [happens right before](https://github.com/leoheck/kiri/blob/main/bin/kiri#L692-L699) the `--remove` cleanup step! Running with `--remove` seems to work just fine.

**Comment by leoheck** [comment]
Remove, removes old folder. not the new one.

**Comment by leoheck** [comment]
Alright, I see what you are talking. It is fixed.

**Comment by leoheck** [comment]
Thank you by the way.

**Comment by edahlseng** [comment]
You're welcome! Thank you for the fix! Confirmed that it's working as expected on my machine now, too!

**Comment by leoheck** [comment]
Awesome
