### ISSUE TITLE
FYI: I created a homebrew recipe for installation on macOS

### ISSUE THREAD

**Issue by edahlseng** [leoheck/kiri#29]
To install:
```shell
# Download a nightly version of KiCad
HOMEBREW_KICAD_APP_PATH="/Applications/KiCad-nightly/KiCad.app" brew install edahlseng/core/kiri
brew link --overwrite kiri
```

There's a recipe for `plotkicadsch`, `KiCad-Diff`, and `kiri` (which depends on the first two). Recipes are stored in my [personal homebrew repository](https://github.com/edahlseng/homebrew-core). Right now I'm using your branch of `KiCad-Diff`.

**Comment by leoheck** [comment]
Nice. I prefer to use the original repos whenever possible. But when I have to work around something that is not working I change the links to my forks until I manage to push some changes/issue reports to these 2 repos. But as far as I remember, Kicad-Diff has merged my PR, so you can set it to use the original repo. 

![image](https://user-images.githubusercontent.com/1277920/147013470-cab066d4-d1dc-4aad-9688-0550ff2dde6f.png)
