### ISSUE TITLE
rename has different syntax on my system

### ISSUE THREAD

**Issue by dsperlich** [leoheck/kiri#51]
Hi,

the layer renaming does not work on my system (gentoo using normal util-linux version of rename). 
Man page state:
       rename [options] expression replacement file...

So i need to change the rename call to get it working:
```diff
diff --git a/bin/kiri b/bin/kiri
index 2603563..ef4f76d 100755
--- a/bin/kiri
+++ b/bin/kiri
@@ -1519,9 +1519,25 @@ generate_layout_artifacts()
                fi
 
                # Rename files folowing format: layer-xx.svg
-               rename "s/${kicad_project_name_1}-/layer-/" "${OUTPUT_DIR_PATH}/${commit_hash_1}/"*.svg &> /dev/null
-               rename "s/${kicad_project_name_2}-/layer-/" "${OUTPUT_DIR_PATH}/${commit_hash_2}/"*.svg &> /dev/null
-
+               rename ${kicad_project_name_1}- layer-  "${OUTPUT_DIR_PATH}/${commit_hash_1}/"*.svg &> /dev/null
+               rename ${kicad_project_name_2}- layer-  "${OUTPUT_DIR_PATH}/${commit_hash_2}/"*.svg &> /dev/null
+
```

Cheers
Dennis

**Comment by leoheck** [comment]
Hi Dennis, could you format your issue report so I can understand it better?

**Comment by leoheck** [comment]
Can you share the version of your rename command?

The one on my systems are:
```bash
➜  rename -V
/usr/bin/rename using File::Rename version 1.30, File::Rename::Options version 1.10
```

**Comment by leoheck** [comment]
My man page states this

![image](https://user-images.githubusercontent.com/1277920/182868109-7dd8e9ef-1a0c-4e7f-ba87-2d1f578c578d.png)

Your commands abod does not have the sed-like regexp that I was looking for.

**Comment by dsperlich** [comment]
Mine is: 
`rename -V
rename from util-linux 2.38`

So interesting and somewhat concerning that Ubuntu uses a different rename than e.g. redhat based linux like rocky. So yours is from perl, mine from util-linux. Difficult...

**Comment by leoheck** [comment]
Found this, https://stackoverflow.com/questions/31408764/using-regex-with-rename-version-from-util-linux

**Comment by leoheck** [comment]
Ah, maybe gentoo have the util-linux rename by default. There is no rename on Ubuntu by default.
Maybe this rename is the the one compatible with the version on Ubuntu.

https://packages.gentoo.org/packages/dev-perl/rename

**Comment by dsperlich** [comment]
Yes this would work for gentoo, even though annoying to require a certain version of such a package, but just checked Rocky Linux (RedHat derivative) and this also has rename from util-linux by default and there is no obvious perl rename.

**Comment by dsperlich** [comment]
It is called emerge. But as gentoo user I would actually prefer not have a install script install dependencies, but rater tell me a list of packages needed. Usually i'm fine translating myself from the ubuntu names though. You consider echo out the list of ubuntu packages needed if the system is not officially supported.

**Comment by leoheck** [comment]
I see and makes sense but then I is kind of harder to make sure the packages are the ones Kiri needs

Since the required rename would be this one:
![image](https://user-images.githubusercontent.com/1277920/182893639-dc769de2-6d59-4212-928b-644e4bf9abcf.png)

Source: https://stackoverflow.com/questions/49267913/renaming-files-using-regular-expressions-linux

**Comment by leoheck** [comment]
Actually I should use a better why to install and check dependencies...

**Comment by leoheck** [comment]
A note regarding the rename command used was added inside the install_dependencies script. I am going to close this issue now, but feel free to reopen it if you still think it is important.
