### ISSUE TITLE
Add support for Linuxmint

### ISSUE THREAD

**Issue by lockencopp** [leoheck/kiri#70]
Support for Linuxmint can be added by wildcarding the debian comparison with `${distro_id_like}` like so:

`if [[ "${distro_id}" == "debian" ]] || [[ "${distro_id_like}" == *"debian"* ]]; then`

as Linuxmint identifies as "ubuntu debian".

https://github.com/leoheck/kiri/blob/7c7958e5fd9a347ee43e6f8a4c5b31ccafa1399c/install_dependencies.sh#L35

**Comment by leoheck** [comment]
Oh, these fuckers always change stupid things.

I will update the script. However your code snippet and your comment are different. Which one works for you?

**Comment by leoheck** [comment]
It is fixed, thanks. Let me know if you find any other issues.
