### ISSUE TITLE
404 on every schematic / PCB SVG

### ISSUE THREAD

**Issue by MarcelRobitaille** [leoheck/kiri#72]
Sorry to bother you again. I'm getting 404 on every schematic SVG. The webpage loads fine otherwise and I'm able to see all my commits. However, I'm not able to see any schematics or PCB. 

![image](https://user-images.githubusercontent.com/8503756/227141838-a7a5c0a1-8b92-4490-a439-32f2f48cbb36.png)

It looks like kiri is looking for these files in `.kiri/_local_/kiri/sch` and `.kiri/_local_/kiri/pcb`. The former does not exist and the latter is an empty folder. However, I do have `.kiri/_local_/tmp.iQjngeGOvB` that has many `.plt` files inside.

**Comment by MarcelRobitaille** [comment]
I am still getting this actually. Now, I have a folder `.kiri/<hash>/sch` and `.kiri/<hash>/pcb`, but the frontend seems to be looking for `.kiri/<hash>/kiri/pcb`. I have an empty folder `.kiri/<hash>/kiri/pcb` but `.kiri/<hash>/kiri/sch` is missing.

**Comment by leoheck** [comment]
Run kiri one time with the flag -r to remove old files. And let me know if it is ok.

**Comment by leoheck** [comment]
I ran it with one of my projects and it with working fine. I have to investigate then. 

Can you use the flags `-r -V -t 3` and share the output here?

**Comment by leoheck** [comment]
@MarcelRobitaille this looks good from my side. Feel free to reopen the issue with extra details if the issue was not fixed for you.

**Comment by leoheck** [comment]
Please, try to update your Kiri using the latest main branch. Ah, maybe your installation did not when well, and maybe there is something missing since you are using Arch.  Do you have your packman history to share here with me so I can update the install_dependencies for your case.. and then we could work together until kiri is working on your system.

**Comment by leoheck** [comment]
There is also an issue with the `rename` command. It should be the `perl-rename`... and it should be. It is fixed in the master too.

**Comment by leoheck** [comment]
Now it seems to be working. This is the latest commit, `25404d7cf9e1c4ac9353bcbd799e5ec613555aa2`

**Comment by leoheck** [comment]
Still have to check how to install Kicad 7 and (check why xdotool is not plotting Kicad 6 files)

**Comment by leoheck** [comment]
@MarcelRobitaille  Thanks for your help so far. 

Is Kiri already working for you? Do you still have issues running it?

**Comment by MarcelRobitaille** [comment]
I'm still trying to get it working. I had problems with the graphical method of plotting the schematic. `plot_kicad_sch` was always exiting with 124. Now I'm trying to use the `kicad-cli`.

**Comment by MarcelRobitaille** [comment]
OK, everything seems to be working now with `kicad-cli`. I had to make some changes to the code though. See #76

**Comment by leoheck** [comment]
Cool awesome.
