### ISSUE TITLE
Check for kicad-cli does not work

### ISSUE THREAD

**Issue by MarcelRobitaille** [leoheck/kiri#76]
In [`generate_schematic_artifacts`](https://github.com/leoheck/kiri/blob/main/bin/kiri#L1499) and [`generate_layout_artifacts`](https://github.com/leoheck/kiri/blob/main/bin/kiri#L1634) there is a test for whether `kicad-cli` exists:

```bash
if [[ -f $(which kicad-cli 2>&1 > /dev/null) ]]
```

Since all output is piped into `/dev/null`, nothing is returned from `which`, so the test for the file's existence fails.

Instead of checking for the existence of `/usr/bin/kicad-cli`, I would recommend `if type kicad-cli` or `if command -v kicad-cli`.

[Stack-Overflow: How can I check if a command exists in a shell script?](https://stackoverflow.com/questions/7522712/how-can-i-check-if-a-command-exists-in-a-shell-script)

**Comment by leoheck** [comment]
lol, this was just a quick test to make this kicad 7 working. please, check the latest version.
