### ISSUE TITLE
Distribution-specific packages

### ISSUE THREAD

**Issue by MarcelRobitaille** [leoheck/kiri#77]
I just wanted to let you know that I packaged [`kiri`](https://aur.archlinux.org/packages/kiri-git) and [`kicad-diff`](https://aur.archlinux.org/packages/kicad-diff-git) for the arch user repositories. 

I think you should also consider making packages for other distributions, like `.deb`, `.rpm`, flatpak, etc. I think that would reduce friction and increase trust for new users of the software. If you are interested, I can help with this. Otherwise, feel free to close this issue.

**Comment by leoheck** [comment]
I don't care about the packages. You can do something, it is fine for me and maybe some users will love it too.
